const actionTypes = {
  GET_TODOS: "GET_TODOS",
  SET_TODOS: "SET_TODOS",
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  SET_MODAL: "SET_MODAL",
  MODAL_CONFIRM: "MODAL_CONFIRM",
  MODAL_CANCEL: "MODAL_CANCEL",
};

export default actionTypes;
